-- 모든 테이블 시스템 컬럼 4개 강제 적용
-- regr_id TEXT NOT NULL DEFAULT 'ADMIN'
-- reg_dtm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
-- modr_id TEXT NOT NULL DEFAULT 'ADMIN'
-- mod_dtm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP

-- ============================================================
-- Group 1: 시스템 컬럼 4개 전부 누락 테이블
-- ============================================================
ALTER TABLE public.approval_queue
  ADD COLUMN IF NOT EXISTS regr_id TEXT        NOT NULL DEFAULT 'ADMIN',
  ADD COLUMN IF NOT EXISTS reg_dtm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS modr_id TEXT        NOT NULL DEFAULT 'ADMIN',
  ADD COLUMN IF NOT EXISTS mod_dtm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE public.events
  ADD COLUMN IF NOT EXISTS regr_id TEXT        NOT NULL DEFAULT 'ADMIN',
  ADD COLUMN IF NOT EXISTS reg_dtm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS modr_id TEXT        NOT NULL DEFAULT 'ADMIN',
  ADD COLUMN IF NOT EXISTS mod_dtm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE public.instruments
  ADD COLUMN IF NOT EXISTS regr_id TEXT        NOT NULL DEFAULT 'ADMIN',
  ADD COLUMN IF NOT EXISTS reg_dtm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS modr_id TEXT        NOT NULL DEFAULT 'ADMIN',
  ADD COLUMN IF NOT EXISTS mod_dtm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE public.participants
  ADD COLUMN IF NOT EXISTS regr_id TEXT        NOT NULL DEFAULT 'ADMIN',
  ADD COLUMN IF NOT EXISTS reg_dtm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS modr_id TEXT        NOT NULL DEFAULT 'ADMIN',
  ADD COLUMN IF NOT EXISTS mod_dtm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS regr_id TEXT        NOT NULL DEFAULT 'ADMIN',
  ADD COLUMN IF NOT EXISTS reg_dtm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS modr_id TEXT        NOT NULL DEFAULT 'ADMIN',
  ADD COLUMN IF NOT EXISTS mod_dtm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE public.role_logs
  ADD COLUMN IF NOT EXISTS regr_id TEXT        NOT NULL DEFAULT 'ADMIN',
  ADD COLUMN IF NOT EXISTS reg_dtm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS modr_id TEXT        NOT NULL DEFAULT 'ADMIN',
  ADD COLUMN IF NOT EXISTS mod_dtm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE public.settlements
  ADD COLUMN IF NOT EXISTS regr_id TEXT        NOT NULL DEFAULT 'ADMIN',
  ADD COLUMN IF NOT EXISTS reg_dtm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS modr_id TEXT        NOT NULL DEFAULT 'ADMIN',
  ADD COLUMN IF NOT EXISTS mod_dtm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE public.sync_log
  ADD COLUMN IF NOT EXISTS regr_id TEXT        NOT NULL DEFAULT 'ADMIN',
  ADD COLUMN IF NOT EXISTS reg_dtm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS modr_id TEXT        NOT NULL DEFAULT 'ADMIN',
  ADD COLUMN IF NOT EXISTS mod_dtm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- ============================================================
-- Group 2: regr_id / modr_id 누락 (reg_dtm, mod_dtm 정상)
-- ============================================================
ALTER TABLE public.brd_ctgr
  ADD COLUMN IF NOT EXISTS regr_id TEXT NOT NULL DEFAULT 'ADMIN',
  ADD COLUMN IF NOT EXISTS modr_id TEXT NOT NULL DEFAULT 'ADMIN';

ALTER TABLE public.sys_user
  ADD COLUMN IF NOT EXISTS regr_id TEXT NOT NULL DEFAULT 'ADMIN',
  ADD COLUMN IF NOT EXISTS modr_id TEXT NOT NULL DEFAULT 'ADMIN';

-- ============================================================
-- Group 3: auth_link_cd — regr_id / modr_id / mod_dtm 누락
-- ============================================================
ALTER TABLE public.auth_link_cd
  ADD COLUMN IF NOT EXISTS regr_id TEXT        NOT NULL DEFAULT 'ADMIN',
  ADD COLUMN IF NOT EXISTS modr_id TEXT        NOT NULL DEFAULT 'ADMIN',
  ADD COLUMN IF NOT EXISTS mod_dtm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN reg_dtm SET DEFAULT CURRENT_TIMESTAMP;

-- ============================================================
-- Group 4: std_* — regr_id / modr_id nullable → NOT NULL DEFAULT 'ADMIN'
-- ============================================================
UPDATE public.std_dic  SET regr_id = 'ADMIN' WHERE regr_id IS NULL;
UPDATE public.std_dic  SET modr_id = 'ADMIN' WHERE modr_id IS NULL;
ALTER TABLE public.std_dic
  ALTER COLUMN regr_id SET NOT NULL,
  ALTER COLUMN regr_id SET DEFAULT 'ADMIN',
  ALTER COLUMN modr_id SET NOT NULL,
  ALTER COLUMN modr_id SET DEFAULT 'ADMIN',
  ALTER COLUMN reg_dtm SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN mod_dtm SET DEFAULT CURRENT_TIMESTAMP;

UPDATE public.std_dom  SET regr_id = 'ADMIN' WHERE regr_id IS NULL;
UPDATE public.std_dom  SET modr_id = 'ADMIN' WHERE modr_id IS NULL;
ALTER TABLE public.std_dom
  ALTER COLUMN regr_id SET NOT NULL,
  ALTER COLUMN regr_id SET DEFAULT 'ADMIN',
  ALTER COLUMN modr_id SET NOT NULL,
  ALTER COLUMN modr_id SET DEFAULT 'ADMIN',
  ALTER COLUMN reg_dtm SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN mod_dtm SET DEFAULT CURRENT_TIMESTAMP;

UPDATE public.std_term SET regr_id = 'ADMIN' WHERE regr_id IS NULL;
UPDATE public.std_term SET modr_id = 'ADMIN' WHERE modr_id IS NULL;
ALTER TABLE public.std_term
  ALTER COLUMN regr_id SET NOT NULL,
  ALTER COLUMN regr_id SET DEFAULT 'ADMIN',
  ALTER COLUMN modr_id SET NOT NULL,
  ALTER COLUMN modr_id SET DEFAULT 'ADMIN',
  ALTER COLUMN reg_dtm SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN mod_dtm SET DEFAULT CURRENT_TIMESTAMP;

-- ============================================================
-- Group 5: pi_pymnt — reg_dtm/mod_dtm nullable → NOT NULL, regr_id/modr_id 추가
-- ============================================================
UPDATE public.pi_pymnt SET reg_dtm = CURRENT_TIMESTAMP WHERE reg_dtm IS NULL;
UPDATE public.pi_pymnt SET mod_dtm = CURRENT_TIMESTAMP WHERE mod_dtm IS NULL;
ALTER TABLE public.pi_pymnt
  ADD COLUMN IF NOT EXISTS regr_id TEXT NOT NULL DEFAULT 'ADMIN',
  ADD COLUMN IF NOT EXISTS modr_id TEXT NOT NULL DEFAULT 'ADMIN',
  ALTER COLUMN reg_dtm SET NOT NULL,
  ALTER COLUMN reg_dtm SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN mod_dtm SET NOT NULL,
  ALTER COLUMN mod_dtm SET DEFAULT CURRENT_TIMESTAMP;
